python_matrix operations in JupyterNotebook

In [9]:
#Install a pippackage in the current Jupyter
import sys
!{sys.executable} -m pip install numpy

                                              0.0/15.0 MB ? eta -:--:--
                                              0.0/15.0 MB 1.3 MB/s eta 0:00:12
                                              0.1/15.0 MB 1.7 MB/s eta 0:00:10
                                              0.2/15.0 MB 2.1 MB/s eta 0:00:08
     -                                        0.5/15.0 MB 3.2 MB/s eta 0:00:05
     -                                        0.6/15.0 MB 3.4 MB/s eta 0:00:05
     --                                       1.0/15.0 MB 4.8 MB/s eta 0:00:03
     ---                                      1.2/15.0 MB 5.0 MB/s eta 0:00:03
     ----                                     1.7/15.0 MB 6.2 MB/s eta 0:00:03
     -----                                    2.3/15.0 MB 7.2 MB/s eta 0:00:02
     ------                                   2.4/15.0 MB 7.4 MB/s eta 0:00:02
     -------                                  2.7/15.0 MB 6.9 MB/s eta 0:00:02
     --------                                 3.3/15.0 MB 7

#使用shape获取矩阵大小,a.T得到转置

In [5]:
import numpy as np
a=np.mat([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a.T)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]


#矩阵乘法运算

In [2]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[1,4],[2,5],[3,6]])
outcome_1=np.dot(A,B)
outcome_2=np.dot(B,A)
print(outcome_1)

print(outcome_2)

[[14 32]
 [32 77]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]


#矩阵加法运算

In [7]:
C=np.array([[23,34,45],[123,345,567],[65,43,32]])
D=np.array([[123,345,456],[32,43,54],[876,654,432]])
print("C+D=\n",C+D)

C+D=
 [[146 379 501]
 [155 388 621]
 [941 697 464]]


#矩阵求trace

In [8]:
E=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.trace(E))

15


#求方阵的行列式det try new features_求逆矩阵

In [5]:
F=np.array([[0,1],[2,3]])
print(np.linalg.det(F))
import numpy as np
Arr=np.array([[2,5],[1,3]])
Arr_inv=np.linalg.inv(Arr)
print(Arr_inv)

-2.0
[[ 3. -5.]
 [-1.  2.]]


#求特征值和特征向量

In [16]:
arr=np.array([[8,1],[4,5]])
w,v=np.linalg.eig(arr)
print("特征值",w)
print("特征向量",v)
print("最大特征值",w[np.argmax(w)])
print("对应的最大特征向量",v[:,np.argmax(w)])

特征值 [9. 4.]
特征向量 [[ 0.70710678 -0.24253563]
 [ 0.70710678  0.9701425 ]]
最大特征值 9.0
对应的最大特征向量 [0.70710678 0.70710678]


#try new features 矩阵求逆

In [3]:
import numpy as np
Arr=np.array([[2,5],[1,3]])
Arr_inv=np.linalg.inv(Arr)
print(Arr_inv)

[[ 3. -5.]
 [-1.  2.]]
